version: "3.2"

services:
  pri-fdo-rv:
    image: andresportainer/pri-fdo-rv:latest
    expose:
      - "8040"
    ports:
      - "8040:8040"
      - "8041:8041"
    environment:
      rv_ssl_keystore-password: Sw2cqdcc1IM
      rv_port: 8040
      rv_database_connection_url: jdbc:h2:tcp://localhost:8050/./target/data/rvs
      rv_database_username: sa
      rv_database_password: ""
      rv_database_port: 8050
      catalina_home: ./target/tomcat
      rv_https_port: 8041
      rv_protocol_scheme: https
      rv_ssl_keystore: certs/ssl.p12
      log4j_configuration_file: log4j2.xml
    volumes:
      - rv-target:/home/fdo/target
    networks:
      - fdonetwork

  pri-fdo-owner:
    image: andresportainer/pri-fdo-owner:latest
    expose:
      - "8042"
    ports:
      - "8042:8042"
      - "8043:8043"
    environment:
      owner_keystore_password: JPmYuPdSYOG8U3a
      owner_api_password: 05EV9CbHbAQANc1t
      owner_ssl_keystore-password: Sw2cqdcc1IM
      ssl_truststore_password: Sw2cqdcc1IM
      owner_to2_port: 8042
      owner_database_connection_url: jdbc:h2:tcp://localhost:8051/./target/data/ops
      owner_database_username: sa
      owner_database_password: ""
      owner_database_port: 8051
      catalina_home: ./target/tomcat
      owner_keystore: ./owner_keystore.p12
      owner_to0_scheduling_enabled: "true"
      owner_to0_scheduling_interval: 300
      owner_to0_rv_blob: http://localhost:8042?ipaddress=127.0.0.1
      owner_svi_values: ./serviceinfo/sample-values
      owner_svi_string: ./serviceinfo/sample-svi.csv
      owner_api_user: apiUser
      ondie_cache: file:///home/fdo/ondie_cache/
      ondie_autoupdate: "false"
      ondie_zip_artifact: https://tsci.intel.com/content/csme.zip
      ondie_check_revocations: "false"
      owner_protocol_scheme: https
      owner_https_port: 8043
      owner_ssl_keystore: certs/ssl.p12
      ssl_truststore: certs/truststore
      ssl_truststore_type: PKCS12
      fido_ssl_mode: TEST
      owner_pub_key_path: owner_pub_keys.pem
      owner2_pub_key_path: owner2_pub_keys.pem
      log4j_configuration_file: log4j2.xml
    volumes:
      - owner-target:/home/fdo/target
    networks:
      - fdonetwork

volumes:
  rv-target:
  owner-target:

networks:
  fdonetwork:
    driver: bridge
